algoritmo "Questão_21"
var
num1, num2, num3: inteiro
inicio
Escreva ("Digite o primeiro número: ")
leia(num1)
Escreva ("Digite o primeiro número: ")
leia(num2)
Escreva ("Digite o primeiro número: ")
leia(num3)

se num1 > num2 entao
   se num1 > num3 entao
      Escreval("O maior número é: ", num1)
   senao
      Escreval("O maior número é: ", num3)
   fimse
senao
   se num2 > num3 entao
      Escreval("O maior número é: ", num2)
   fimse
fimse


fimalgoritmo
